---
# tasks file for henriquemc.eclipse

- name: creating temp dir
  file: path="{{ eclipse_dir_tmp }}" state=directory

- name: download eclipse
  get_url:
      url=" http://download.eclipse.org/technology/epp/downloads/release/{{eclipse_release_name}}/{{eclipse_release_version}}/eclipse-modeling-{{eclipse_release_name}}-{{eclipse_release_version}}-linux-gtk-x86_64.tar.gz"
      dest="{{ eclipse_dir_tmp }}/{{eclipse_release_name}}.tar.gz"
  register: eclipse_download

- name: directory for extract
  file: path="{{eclipse_dir_tmp}}/eclipse-{{eclipse_release_name}}" state=directory

- name: Extract archive eclipse
  unarchive: src={{ eclipse_dir_tmp }}/{{eclipse_release_name}}.tar.gz 
             dest={{eclipse_dir_tmp}}/eclipse-{{eclipse_release_name}} 
             copy=no 
  register: eclipse_extracted
  when: eclipse_download.changed
        
- name: stat for result dir
  stat: path={{eclipse_base_dir}}/eclipse-{{eclipse_release_name}}
  register: eclipse_dest_dir_stat

- name: Move temporary eclipse to destiny folder
  command: mv {{eclipse_dir_tmp}}/eclipse-{{eclipse_release_name}}/eclipse/ {{eclipse_base_dir}}/eclipse-{{eclipse_release_name}}
  when: not eclipse_dest_dir_stat.stat.exists and eclipse_extracted.changed
  
- name: delete tmp folder
  file: path="{{eclipse_dir_tmp}}" state=absent        

- name: stat for eclipse
  stat: path={{eclipse_base_dir}}/eclipse-{{eclipse_release_name}}/eclipse
  register: eclipse_executable

- name: Install plugins
  command: "{{eclipse_base_dir}}/eclipse-{{eclipse_release_name}}/eclipse -nosplash \
     -application org.eclipse.equinox.p2.director \
     -destination {{eclipse_base_dir}}/eclipse-{{eclipse_release_name}} \
     -repository {{item.repository}}  \
    -installIU {{item.features}} "
  ignore_errors: True
  when: eclipse_executable.stat.exists
  with_items: pluginsForInstall